### ISSUE TITLE
Conversion from double to int

### ISSUE THREAD

**Issue by Torrintino** [Torrintino/networkit#1]
For some reason I assumed, that node ID's are double, but they are actually uint64_t, see: Networkit Namespace reference, typedefs
The types right now are incorrect, we should either use some long type, or just directly uint64_t to be on the safe side.
@niklasdeckers One open question: Can we assume, that the largest node ID is smaller/equal to the graph size? If not, that might cause problems with hashing/indexing. Maybe we ask the advisors on Thursday. (Side note: I activated issues for the repo, to make communication easier).

**Comment by Torrintino** [comment]
I tested it today and we can assume that.
Fix has been committed. Case closed.

**Comment by niklasdeckers** [comment]
One remark on this: Seems to require remapNodes=true in https://networkit.github.io/dev-docs/cpp_api/class_networ_kit_1_1_s_n_a_p_graph_reader.html

**Comment by Torrintino** [comment]
I don't know how exactly SNAP looks like. So far I have created the graphs manually and forget, that I may not be able to make some assumptions on the SNAP reader. 
That a node ID may not be larger than the graph size is a general requirement by the graph data structure. However, if we don't require, that they are consecutive, we may waste a lot of space. The documentation notes, that if remapNodes=false, the benchmark might be 2x faster. So is this a space/time trade off? I think our algorithm doesn't require the node ID's to be consecutive.

Question: When we read in a SNAP file, do we know beforehand how many nodes we read (using header information or so)? If that's the case we might save time preallocating memory.
