### ISSUE TITLE
Inadequate unpair function

### ISSUE THREAD

**Issue by Torrintino** [Torrintino/networkit#2]
The current unpair function will create a unique integer for any u, v. However unpair(u, v) and unpair(v, u) should have the same value, because they should be hashed and identified as the same edge.

The actual requirement is, that unpair creates a unique int for each edge, however as we have an undirected graph (u, v) and (v, u) are the same.

**Comment by niklasdeckers** [comment]
How about this: inside upair you swap u,v if required such that u<=v, then you compute u*n_nodes+v?

**Comment by Torrintino** [comment]
Good idea, I overlooked that I can just swap u and v.
Fixed.
