### ISSUE TITLE
Compute support

### ISSUE THREAD

**Issue by Torrintino** [Torrintino/networkit#3]
I wrote a test for the compute_support function ([Dev 3787eba4]) and it fails, as the equality assertions do not hold. Can you please have a look?

**Comment by niklasdeckers** [comment]
Sorry, can't find this commit... :/
What is the entry point? Will g.sortEdges(); be executed first?

**Comment by Torrintino** [comment]
Here is the link to the commit adding the test: https://github.com/Torrintino/networkit/commit/3787eba40f8d37730adf789250af8186f551b47a
In line 65 the edges get sorted. Then I'm doing three consecutive calls of compute_support. Does the order matter, in which I call the function?
